name: Deploy to FTP

on:
  push:
    branches:
      - master  # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Upload to FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ../workspace
        remoteDir: /domains/nekodeveloper.com/public_html/reimagineheritage/html2
        options: "--delete --asci"
